//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onetodo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoneList
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Dosage { get; set; }
        public int Calories { get; set; }
        public bool Vitamins { get; set; }
        public int MoneySpent { get; set; }
    }
}
